### ISSUE TITLE
DatasetNotFoundException - salesforce2hadoop

### ISSUE THREAD

**Issue by kanav-narula** [datadudes/salesforce2hadoop#4] opened 2016-04-06 10:50 UTC
Hi [@Daan] : 

We are using salesforce2hadoop library for exporting data from salesforce to hadoop.
We are using the below command for the same.

**sudo java -jar salesforce2hadoop-assembly-1.0.jar init -u myUsername -p myPassword -b /home/nfsuser/imports/salesforce -w /home/sanjay/Desktop/enterprise.wsdl -s /home/nfsuser/imports/salesforce/account Account**

We are getting the below error 

**org.kitesdk.data.DatasetNotFoundException: Unknown dataset URI: 
/home/nfsuser/imports/salesforce/account. Check that JARs for null datasets are on the classpath.**

Need your help in above issue.

Thanks
Kanav Narula

**Comment by AmritaKv** [comment] 2016-08-25 18:53
I am getting the same error with latest jar, but I see the issue is closed, is it resolved?

**Comment by daan** [comment] 2016-08-26 00:57
hi,

sometimes i receive these messages, I think you confuse me with someone else because i don’t do hadoop.

Thanks,
daniel

**Comment by AmritaKv** [comment] 2016-08-26 02:21
@DandyDev , I am getting the same error with latest jar ,I saw you close it but is it resolved?

**Comment by DandyDev** [comment] 2016-08-26 09:53
I closed it because it was an old issue and I initially failed to have a look at it, and didn't get any follow up on it.
I will repone it if it's still an issue! One problem is, however, that I don't have a Salesforce instance anymore to test this project. But I will see what I can do.

**Comment by DandyDev** [comment] 2016-08-26 09:59
Update: I think I know what's going on. You have to provide a _full and valid_ Hadoop-compliant filepath. That means that the protocol has to be included, for both the base path for the data and the path to the statefile. (See [Data import directory](https://github.com/datadudes/salesforce2hadoop#initial-data-import) )

Examples:

```
hdfs://hostname-of-namenode:port/path/to/dir
file:///path/to/dir
```

The first one writes to HDFS, the second to the local filesystem. Any Hadoop/Kite compliant FS should be supported (although I've only tested HDFS and local fs)

Can you let me know if that resolves the issue?

**Comment by AmritaKv** [comment] 2016-08-26 14:56
@DandyDev You were correct!Specifying the protocol for local fs helped. 
But now leading to another configuration issue, the apiVersion is hardcoded to 32.
I am creating another issue for it to change to be configurable like the Base url

**Closed** 2016-12-05 20:20 UTC
